### ISSUE TITLE
Pretrained Models release request.

### ISSUE THREAD

**Issue by muhammad-ahmed-ghani** [facebookresearch/StyleNeRF#12] opened 2022-03-18 16:41 UTC
Hi @MultiPath can you please upload the pretrained models link here.

**Comment by ByeongkiJeong** [comment] 2022-03-19 12:07
Duplicate of #1 and #6

**Comment by MultiPath** [comment] 2022-03-20 21:43
Hi, I am sorry for the delay. I had some issues with my AWS account which will serves our pretrained model and data. I need to wait people to fix it before I can upload the checkpoints.

**Comment by AK391** [comment] 2022-03-20 21:48
@MultiPath also check out Hugging Face for uploading checkpoints, I can help with this. The checkpoints can be uploaded like this https://huggingface.co/akhaliq/jojogan-stylegan2-ffhq-config-f/blob/main/stylegan2-ffhq-config-f.pt

**Comment by MultiPath** [comment] 2022-03-20 21:51
@AK391 Thanks! Do you also have some instructions for that? Is this different from Space which is for demo?

**Comment by AK391** [comment] 2022-03-20 21:56
@MultiPath Yes, here are some guides, spaces are different from models as they can support gradio interfaces for inference

How to add a Space: https://huggingface.co/blog/gradio-spaces
how to add models: https://huggingface.co/docs/hub/adding-a-model
uploading a dataset: https://huggingface.co/docs/datasets/upload_dataset.html

some more examples
github: https://github.com/salesforce/BLIP
Spaces: https://huggingface.co/spaces/Salesforce/BLIP

github: https://github.com/facebookresearch/omnivore
Spaces: https://huggingface.co/spaces/akhaliq/omnivore

**Comment by AK391** [comment] 2022-03-20 22:05
@MultiPath also there is a facebook AI organization of huggingface https://huggingface.co/facebook which already has 248 models and 6 spaces if you would like to upload the models there, would just need to join the organization and I can accept the request or you can create your own account and put the models under there.

**Comment by MultiPath** [comment] 2022-03-20 22:07
Thanks. I usually upload checkpoints/datasets to AWS storage. However, my account did not work recently I noticed. I am still waiting for people to fix that. I will check this, and join trying the organization on huggingface. Thank you very much!

**Comment by MultiPath** [comment] 2022-03-22 04:16
Hi, I have added one checkpoint of FFHQ. In the following days, I am also adding more checkpoints to huggingface models. Thanks for your very kind patience!

**Closed as completed by MultiPath** 2022-03-22 04:16 UTC
